"""add credit transaction sequence id

Revision ID: 0aaf30d66bb3
Revises: 96f59ed2ba52
Create Date: 2026-05-06 05:59:09.329028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aaf30d66bb3'
down_revision: Union[str, Sequence[str], None] = '96f59ed2ba52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transactions', sa.Column('sequence_id', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    op.create_index(op.f('ix_credit_transactions_sequence_id'), 'credit_transactions', ['sequence_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_transactions_sequence_id'), table_name='credit_transactions')
    op.drop_column('credit_transactions', 'sequence_id')
    # ### end Alembic commands ###
