"""add asset fields to generation images

Revision ID: 30235fc7cf43
Revises: 0aaf30d66bb3
Create Date: 2026-05-10 18:13:18.679427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30235fc7cf43'
down_revision: Union[str, Sequence[str], None] = '0aaf30d66bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_images', sa.Column('asset_type', sa.String(length=50), nullable=False, server_default="image",))
    op.add_column('generation_images', sa.Column('gcs_uri', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_generation_images_asset_type'), 'generation_images', ['asset_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_images_asset_type'), table_name='generation_images')
    op.drop_column('generation_images', 'gcs_uri')
    op.drop_column('generation_images', 'asset_type')
    # ### end Alembic commands ###
