"""cleanup miniapp database schema

Revision ID: 8eb702988fcd
Revises: 30235fc7cf43
Create Date: 2026-05-10 23:47:20.888899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8eb702988fcd'
down_revision: Union[str, Sequence[str], None] = '30235fc7cf43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute(
        """
        UPDATE generation_images
        SET mime_type = CASE
            WHEN lower(file_path) LIKE '%.jpg' THEN 'image/jpeg'
            WHEN lower(file_path) LIKE '%.jpeg' THEN 'image/jpeg'
            WHEN lower(file_path) LIKE '%.png' THEN 'image/png'
            WHEN lower(file_path) LIKE '%.webp' THEN 'image/webp'
            ELSE mime_type
        END
        WHERE mime_type IS NULL
        """
    )

    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_processed_updates_created_at'), table_name='processed_updates')
    op.drop_index(op.f('ix_processed_updates_telegram_id'), table_name='processed_updates')
    op.drop_table('processed_updates')
    op.drop_column('generation_images', 'telegram_file_id')
    op.drop_column('users', 'free_generations_used')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'free_generations_used',
            sa.INTEGER(),
            server_default='0',
            nullable=False,
        ),
    )
    op.alter_column('users', 'free_generations_used', server_default=None)
    op.add_column('generation_images', sa.Column('telegram_file_id', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.create_table('processed_updates',
    sa.Column('update_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], name=op.f('processed_updates_telegram_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('update_id', name=op.f('processed_updates_pkey'))
    )
    op.create_index(op.f('ix_processed_updates_telegram_id'), 'processed_updates', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_processed_updates_created_at'), 'processed_updates', ['created_at'], unique=False)
    op.create_table('user_sessions',
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], name=op.f('user_sessions_telegram_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('telegram_id', name=op.f('user_sessions_pkey'))
    )
    # ### end Alembic commands ###
