"""add payment provider fields

Revision ID: 96f59ed2ba52
Revises: c020d32c6e3b
Create Date: 2026-05-04 05:09:57.222099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f59ed2ba52'
down_revision: Union[str, Sequence[str], None] = 'c020d32c6e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('provider_payment_id', sa.String(length=255), nullable=True))
    op.add_column('purchases', sa.Column('payment_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'payment_url')
    op.drop_column('purchases', 'provider_payment_id')
    # ### end Alembic commands ###
