"""create main tables

Revision ID: a81025a9fd99
Revises: 098965724109
Create Date: 2026-05-03 16:39:16.351671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a81025a9fd99'
down_revision: Union[str, Sequence[str], None] = '098965724109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('target_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_telegram_id'), 'audit_log', ['actor_telegram_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_target_telegram_id'), 'audit_log', ['target_telegram_id'], unique=False)
    op.create_table('processed_updates',
    sa.Column('update_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('update_id')
    )
    op.create_index(op.f('ix_processed_updates_created_at'), 'processed_updates', ['created_at'], unique=False)
    op.create_index(op.f('ix_processed_updates_telegram_id'), 'processed_updates', ['telegram_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELED', name='generation_status'), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('input_images_cnt', sa.Integer(), nullable=False),
    sa.Column('cost_credits', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_created_at'), 'generations', ['created_at'], unique=False)
    op.create_index(op.f('ix_generations_status'), 'generations', ['status'], unique=False)
    op.create_index(op.f('ix_generations_telegram_id'), 'generations', ['telegram_id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_rub', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'MANUAL', name='purchase_status'), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_created_at'), 'purchases', ['created_at'], unique=False)
    op.create_index(op.f('ix_purchases_status'), 'purchases', ['status'], unique=False)
    op.create_index(op.f('ix_purchases_telegram_id'), 'purchases', ['telegram_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('generation_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('GRANT', 'SPEND', 'REFUND', 'PURCHASE', 'ADMIN_ADJUSTMENT', name='credit_transaction_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_created_at'), 'credit_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_transactions_generation_id'), 'credit_transactions', ['generation_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_telegram_id'), 'credit_transactions', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_type'), 'credit_transactions', ['type'], unique=False)
    op.create_table('generation_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('INPUT', 'OUTPUT', name='generation_image_role'), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_images_generation_id'), 'generation_images', ['generation_id'], unique=False)
    op.create_index(op.f('ix_generation_images_role'), 'generation_images', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_images_role'), table_name='generation_images')
    op.drop_index(op.f('ix_generation_images_generation_id'), table_name='generation_images')
    op.drop_table('generation_images')
    op.drop_index(op.f('ix_credit_transactions_type'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_telegram_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_generation_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_created_at'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_purchases_telegram_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_status'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_created_at'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_generations_telegram_id'), table_name='generations')
    op.drop_index(op.f('ix_generations_status'), table_name='generations')
    op.drop_index(op.f('ix_generations_created_at'), table_name='generations')
    op.drop_table('generations')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_processed_updates_telegram_id'), table_name='processed_updates')
    op.drop_index(op.f('ix_processed_updates_created_at'), table_name='processed_updates')
    op.drop_table('processed_updates')
    op.drop_index(op.f('ix_audit_log_target_telegram_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_telegram_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
