"""add relationships

Revision ID: c020d32c6e3b
Revises: a81025a9fd99
Create Date: 2026-05-04 02:08:42.031264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c020d32c6e3b'
down_revision: Union[str, Sequence[str], None] = 'a81025a9fd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'audit_log', 'users', ['target_telegram_id'], ['telegram_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_log', 'users', ['actor_telegram_id'], ['telegram_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'processed_updates', 'users', ['telegram_id'], ['telegram_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_sessions', 'users', ['telegram_id'], ['telegram_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_constraint(None, 'processed_updates', type_='foreignkey')
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    # ### end Alembic commands ###
